cache:
  key: common-cache
  paths:
    - .cache/

stages:
  - prebuild
  - run

build-image:
  stage: prebuild
  image: ecohealthalliance/docker-compose-git-crypt
  services:
    - docker:19.03.1-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --build-arg GITHUB_PAT=$GITHUB_PAT --build-arg PKG_COMMIT=$PKG_COMMIT --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    changes:
      - Dockerfile
      - DESCRIPTION

nightly:
  stage: run
  image: $CI_REGISTRY_IMAGE:latest
  before_script:
  - echo $GIT_CRYPT_KEY64 > git_crypt_key.key64 && base64 -d git_crypt_key.key64 > git_crypt_key.key && git-crypt unlock git_crypt_key.key
  only:
    - schedules
  artifacts:
    name: "$CI_COMMIT_REF_SLUG"
    paths:
    - data/
  script:
    - ./download-archive-tables.R

